[package]
name = "game_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_shared = { path = "../game_shared" }
bevy =  { version = "0.12.1", features = ["dynamic_linking"] } 

